project:
  type: website
  output-dir: docs

website:
  title: "लोकसमन्वय प्रतिष्ठान"
  site-url: "https://lsm-p.github.io/Loksamanway-Pratisthan-mr"
  navbar:
    logo: logo.jpg
    right:
      - href: index.qmd
        text: HOME
      - href: mission.qmd
        text: आमचे ध्येय
      - href: history.qmd
        text: इतिहास
      - href: work.qmd
        text: आमचे काम
      - href: people.qmd
        text: लोक
      - href: contact.qmd
        text: संपर्क
      - text: "English 🌍"
        href: https://lsm-p.github.io/Loksamanway-Pratisthan/

html-head:
  - link:
      rel: stylesheet
      href: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css

format:
  html:
    theme: lux
    css: styles.css
